version: $OPENHOTEL_VERSION
name: $OPENHOTEL_NAME
description: $OPENHOTEL_DESCRIPTION
port: $OPENHOTEL_PORT
limits:
  players: $OPENHOTEL_LIMITS_PLAYERS
auth:
  enabled: $OPENHOTEL_AUTH_ENABLED
  licenseToken: $OPENHOTEL_AUTH_LICENSE_TOKEN
  api: $OPENHOTEL_AUTH_API
onet:
  enabled: $OPENHOTEL_ONET_ENABLED
  api: $OPENHOTEL_ONET_API
